// Ikon aplikasi = Font Awesome Free (solid) sebagai SVG — bukan emoji (emoji tampil beda di tiap HP).
// Pakai nama semantik: <Icon name="warehouse" />. Hanya ikon yang diimpor di sini ikut ke bundle.
// Font Awesome Free icons: CC BY 4.0 — https://fontawesome.com/license/free
import {
  faArrowRightFromBracket,
  faArrowRightToBracket,
  faArrowUpRightFromSquare,
  faArrowsRotate,
  faBasketShopping,
  faBell,
  faBoxOpen,
  faCamera,
  faCartShopping,
  faChartColumn,
  faChartLine,
  faCheck,
  faCircleCheck,
  faCircleQuestion,
  faClipboardList,
  faDesktop,
  faDownload,
  faFileInvoice,
  faGear,
  faHouse,
  faInbox,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMobileScreenButton,
  faPenToSquare,
  faPlus,
  faReceipt,
  faRightLeft,
  faRotateLeft,
  faShuffle,
  faSliders,
  faSpinner,
  faTrashCan,
  faTriangleExclamation,
  faTruckRampBox,
  faUser,
  faWarehouse,
  faXmark
} from '@fortawesome/free-solid-svg-icons'

export const ICONS = {
  // navigasi & menu
  home: faHouse,
  warehouse: faWarehouse,
  movement: faChartLine,
  plus: faPlus,
  list: faClipboardList,
  settings: faGear,
  bell: faBell,
  report: faChartColumn,
  user: faUser,
  // jenis dokumen
  'request-transfer': faShuffle,
  cart: faCartShopping,
  'stock-in': faArrowRightToBracket,
  'stock-out': faArrowRightFromBracket,
  transfer: faRightLeft,
  receive: faTruckRampBox,
  return: faRotateLeft,
  quotation: faFileInvoice,
  // aksi & status
  search: faMagnifyingGlass,
  camera: faCamera,
  close: faXmark,
  refresh: faArrowsRotate,
  trash: faTrashCan,
  filter: faSliders,
  check: faCheck,
  'check-circle': faCircleCheck,
  warning: faTriangleExclamation,
  lock: faLock,
  location: faLocationDot,
  note: faPenToSquare,
  desk: faDesktop,
  external: faArrowUpRightFromSquare,
  download: faDownload,
  install: faMobileScreenButton,
  loading: faSpinner,
  // kosong / placeholder
  box: faBoxOpen,
  inbox: faInbox,
  receipt: faReceipt,
  basket: faBasketShopping,
  question: faCircleQuestion
}
